# hints.toml
[Absolon]
hint = "Dhani god of the great deep"
[AbsolonsDream]
hint = "Kuraghan flagship"
[Aeronauts]
hint = "Daring sky captains who trade danger for speed and freedom among the clouds."
[Alif]
hint = "A member of the Cintari, Kassai's close friend."
[Alshoni]
hint = "A faction founded by a particular branch of the Royal Bloodline, a clan brought together by blood ties, headed up by Lord Wizard Chiyo, cousin to the Emperor."
[Ankis]
hint = "The crystalline creature does not bleed. It shatters. Its teeth are harder than stone, with serrated edges and a needle-like tip to tear through flesh. Its limbs are long and thin, with sharp points to allow it to grip onto most surfaces, and scale the difficult terrain of the Savage Lands."
[Ashvahan]
hint = "The Capital of Volcor."
[Bellona]
hint = "The Wartune Herald"
[Braumeister]
hint = "Elite brewers of Aria making spirits which possess unique effects"
[Brawnhide]
hint = "A giant, furred beast with long, thick canines, and small, dark eyes."
[Cintari]
hint = "A group of bloodthirsty brigands who seek the thrill of battle."
[Chiyo]
hint = "Lord Wizard, Head of the Alshoni faction and cousin to the Emperor."
[Chul]
hint = "General who betrayed Kassai's family."
[Cogwerx]
hint = "Cogwerx, credited with inventing steam technology and revolutionising Metrix through steam compression for energy, is largely responsible for the city's success and development."
[Coppertown]
hint = "Coppertown, a southern district of Metrix nestled between vast strip mines, is a working-class community with a large population."
[Davnir]
hint = "Ancient of Earth and Lightning"
[Deshvahan]
hint = "A city in Volcor."
[DhaniEmpire]
hint = "A fallen civilisation once ruled by an arcane empress, whose mastery of aether ended in cataclysmic ruin."
[Dracai]
hint = "The Dracai are bestowed names that are free of any restrictions, conventions or stigma, granted positions in the Royal Court of Volcor by the Emperor."
[Dreadnought]
hint = "Gravy Bones' ship"
[EastRise]
hint = "The majority of this Metrix sector is devoted to parks and entertainment complexes"
[Enion]
hint = "The Armory of Ancients, and Training Ground of Champions"
[Ezu]
hint = "A faction headed up by Chancellor Yama."
[fai-mother]
hint = "Min of the Forest of Flames."
[Fayyad]
hint = "A member of the Cintari, Kassai's close friend."
[Fianna]
hint = "Tall creature, with long flowing tails, tough skin, and massive antlers crowning the top of their head."
[FiddlersGreen]
hint = "An imaginary place where every immortal's whim shall be tended to by demure merfolk."
[TheFlow]
hint = "A wild, unpredictable force of nature in Aria, the Flow shapes the landscape around it as it ebbs and flows."
[GoldenGoose]
hint = "A sleek airship"
[GoldkissRum]
hint = "Bright with a rich golden flavor, this is the most popular drink served at the Kraken's Barrel."
[Gougemoor]
hint = "The edge of the Savage Lands, home to the Deathmatch arena."
[Hoikers]
hint = "Giant, acid-spitting scallops"
[Ikaru]
hint = "One of the prestigious houses of Misteria; the House of Blossoms."
[Infernai]
hint = "Aesir of Flames"
[Jing]
hint = "Xilin and Ira's brother."
[Kayat]
hint = "An illusionist, boss of the Dust Runners."
[Korshem]
hint = "A massive tree at the heart of Aria that shelters all who live amongst its leaves."
[Kuraghan]
hint = "A fanatical pirate cult formed from reconditioned convicts, the Kuraghan worship the sea god Absolon and believe dying in battle earns them an afterlife of endless pleasure."
[Meep]
hint = "Tiny, mischievous creatures are recognised by their long limbs and tails, and colourful feather crests."
[Mendacity]
hint = "A corporation that maintains control of the media, funding almost every radio station and newspaper in the city."
[Min]
hint = "Fai's Mother."
[MountHeroic]
hint = "A mountain which towers above the forests of eastern Aria"
[Nasreth]
hint = "The Soul Harrower, an Embra"
[Nocetes]
hint = "Dhani death god"
[NorthernRealms]
hint = "A region of Solana"
[Sada]
hint = "Kassai's sorceress friend and member of the Cintari."
[Sol]
hint = "Aesir of Light"
[Southmaw]
hint = "Southmaw Asylum is a laboratory of horrors where the orphaned and discarded of the Pits beneath Metrix are subjected to nightmarish experiments."
[SyntheaTeklo]
hint = "Teklo Industries CEO"
[SuperSlam]
hint = "A deadly combat tournament where fighters battle in the Deathmatch Arena for glory and bloodsport."
[Raven]
hint = "Aesir of Chaos"
[Redmoor]
hint = "The Redmoors are Boltyn's cousins."
[Rosetta]
hint = "An Order of powerful spell weavers that once stood alongside the likes of the Ollin and the Seers."
[Ryoki]
hint = "These are small creatures, similar in appearance to fish, that inhabit the lava streams and rivers of Volcor. Despite the immense heat, these creatures thrive in the extreme conditions, lurking beneath the glowing surface of the magma. While their scales are almost black, their 'fins' catch alight when they break the surface of the lava, leaping from stream to stream."
[Savai]
hint = "Lord Merchant of Deshvahan."
[Sayashi]
hint = "Special force of loyal ninjas dedicated to hunting those responsible for the Emperor's death."
[Sirens]
hint = "Enchanting merfolk who lure sailors with song and beauty - gifts please them, but poor offerings may cost you dearly."
[Skera]
hint = "One of the Savage Lands' most skilled predators, they are almost completely nocturnal, relying on the darkness to help mask their movements while stalking prey. Their four eyes are likely to help it see in the dark, in order to hunt its prey."
[Sutcliffe]
hint = "Lord Sutcliffe pursued arcane knowledge despite lacking aether affinity, creating the Arknight project to unlock magical abilities. Betrayed by his creation, Viserai, he was killed and now exists trapped in a skull, tormented and longing for revenge."
[tallics]
hint = "The Metrix currency"
[TeklaticDynamism]
hint = "Energy source invented by Professor Teklovossen"
[TekloIndustries]
hint = "Teklo Industries, a recent entrant to the steamtech industry, is acclaimed for its innovative products and cutting-edge designs driven by a constantly experimenting R&D team."
[TheFoundry]
hint = "An independent radio station, one of the few in Metrix that remains free of Mendacity control."
[Thiroux]
hint = "Dash's mother"
[TropalDhani]
hint = "A legendary city said to have survived the Dhani empire's collapse, hiding its lost magic and treasures in the most perilous ruins."
[Vitreo]
hint = "A majestic creature with a thick mane, crowned with a series of large crystals that grow out from the top of its skull."
[Volcai]
hint = "The Volcai are the more limited social class of Volcor; their names are homogeneous, ending in _ai_ as a mark of their Volcai origin status."
[Xilin]
hint = "Ira and Jing's brother."
[Yama]
hint = "Lord Chancellor and Head of the Ezu faction."
[Yvor]
hint = "Ancient of Lightning and Ice"
